Uppercase CCOUCH environment variables as per new convention

diff --git a/bin/picgrid-compose-image-archives b/bin/picgrid-compose-image-archives
--- a/bin/picgrid-compose-image-archives
+++ b/bin/picgrid-compose-image-archives
@@ -26,8 +26,8 @@ do
 done
 
 
-if [ -z "${ccouch_repo_dir+x}" ] ; then
-    echo "$self_name: error: ccouch_repo_dir not set" >&2
+if [ -z "${CCOUCH_REPO_DIR+x}" ] ; then
+    echo "$self_name: error: CCOUCH_REPO_DIR not set" >&2
     exit 1
 fi
 if [ -z "${archive_info_dir+x}" ] ; then
diff --git a/bin/rsync-push-ccouch-heads b/bin/rsync-push-ccouch-heads
--- a/bin/rsync-push-ccouch-heads
+++ b/bin/rsync-push-ccouch-heads
@@ -4,17 +4,17 @@ set -euo pipefail
 
 self_name="$(basename "$0")"
 
-if [ -z "${ccouch_repo_name+x}" ]
+if [ -z "${CCOUCH_REPO_NAME+x}" ]
 then
-    echo "$selfname: error: ccouch_repo_name not specified" >&2
+    echo "$selfname: error: CCOUCH_REPO_NAME not specified" >&2
     exit 1
 fi
 
 # Don't propagate error until after both have been tried, maybe in parallel.
 
 rsync --ignore-existing -rt \
-      $HOME/.ccouch/heads/$ccouch_repo_name/ \
-      tog@fs.marvin.nuke24.net:/home/tog/.ccouch/heads/$ccouch_repo_name/
+      $HOME/.ccouch/heads/$CCOUCH_REPO_NAME/ \
+      tog@fs.marvin.nuke24.net:/home/tog/.ccouch/heads/$CCOUCH_REPO_NAME/
 rsync --ignore-existing -rt \
-      $HOME/.ccouch/heads/$ccouch_repo_name/ \
-      tog@zappie1.nuke24.net:/home/tog/.ccouch/heads/$ccouch_repo_name/
+      $HOME/.ccouch/heads/$CCOUCH_REPO_NAME/ \
+      tog@zappie1.nuke24.net:/home/tog/.ccouch/heads/$CCOUCH_REPO_NAME/
diff --git a/bin/store-tog-music-archive b/bin/store-tog-music-archive
--- a/bin/store-tog-music-archive
+++ b/bin/store-tog-music-archive
@@ -4,13 +4,13 @@ set -euo pipefail
 
 self_name="$(basename "$0")"
 
-if [ -z "${ccouch_repo_name+x}" ]
+if [ -z "${CCOUCH_REPO_NAME+x}" ]
 then
-    echo "$selfname: error: ccouch_repo_name not specified" >&2
+    echo "$selfname: error: CCOUCH_REPO_NAME not specified" >&2
     exit 1
 fi
 
-commit_message="TOGoS music archive on $ccouch_repo_name"
+commit_message="TOGoS music archive on $CCOUCH_REPO_NAME"
 
 while [[ $# > 0 ]]
 do
